apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: signal-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: signal-db
    spec:
      containers:
        - name: postgres
          image: postgres:10
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: db
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: signal-db-all
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: signal-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: signal-redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
