apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: signal-secrets
data:
  APN_BUNDLEID: MUST_PROVIDE
  APN_CERT: MUST_PROVIDE
  APN_KEY: MUST_PROVIDE
  CCSM_PARTNER_TOKEN: MUST_PROVIDE
  GCM_APIKEY: MUST_PROVIDE
  GCM_SENDERID: MUST_PROVIDE
  S3_ACCESSKEY: MUST_PROVIDE
  S3_ACCESSSECRET: MUST_PROVIDE
  S3_ATTACHMENTSBUCKET: MUST_PROVIDE
  SENTRY_DSN: MUST_PROVIDE
