kind: Service
apiVersion: v1
metadata:
  name: signal-db
spec:
  selector:
    app: signal-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
kind: Service
apiVersion: v1
metadata:
  name: signal-redis
spec:
  selector:
    app: signal-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
kind: Service
apiVersion: v1
metadata:
  name: signal-app-private
spec:
  ports:
  - protocol: TCP
    port: 8180
    targetPort: 8180
  selector:
    app: signal-app
---
kind: Service
apiVersion: v1
metadata:
  name: signal-app-public
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8180
  selector:
    app: signal-app
