kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: signal-db-all
  labels:
    app: signal-db
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
