push:
  queueSize: # Size of push pending queue

cache: # Redis server configuration for cache cluster
  url:

directory: # Redis server configuration for directory cluster
  url:

messageStore: # Postgresql database configuration for message store
  driverClass: org.postgresql.Driver
  user:
  password:
  url:

s3: # AWS S3 configuration
  accessKey:
  accessSecret:
  attachmentsBucket:

database: # Postgresql database configuration
  driverClass: org.postgresql.Driver
  user:
  password:
  url:

apn: # Apple Push Notifications configuration
  bundleId:
  pushCertificate:
  pushKey:

gcm: # GCM Configuration
  senderId:
  apiKey:
