logging:
    level: INFO

twilio:
    numbers:
        - PLACEHOLDER
    accountId: MUST_SET
    accountToken: MUST_SET
    localDomain: MUST_SET

redphone:
    authKey: #not-appliciable

push:
  host: localhost
  port: 9090
  username: MUST_SET
  password: MUST_SET

s3:
    accessKey: MUST_SET
    accessSecret: MUST_SET
    attachmentsBucket: MUST_SET

server:
    applicationConnectors:
        - type: http
          port: 8180

    adminConnectors:
        - type: http
          port: 8181

directory:
    url: "redis://localhost:6379/0"

cache:
    url: "redis://localhost:6379/1"

messageStore:
    driverClass: org.postgresql.Driver
    properties:
        charSet: UTF-8

database:
    driverClass: org.postgresql.Driver
    properties:
        charSet: UTF-8

limits:
    prekeys:
      bucketSize: 100
      leakRatePerMinute: 50

    messages:
      bucketSize: 1000
      leakRatePerMinute: 500

    attachments:
      bucketSize: 1000
      leakRatePerMinute: 100

    allocateDevice:
      bucketSize: 10
      leakRatePerMinute: 5

    verifyDevice:
      bucketSize: 10
      leakRatePerMinute: 5
