logging:
    level: INFO
    appenders:
        - type: console
          threshold: ERROR
        - type: console
          threshold: ALL

trusted:
    partners:
        - name: PLACEHOLDER

push:
    queueSize: 200

gcm:
    apiKey: MUST_BE_SET

apn:
    bundleId: MUST_BE_SET
    pushCertificate: MUST_BE_SET
    pushKey: MUST_BE_SET
 
s3:
    accessKey: MUST_SET_S3_ACCESSKEY
    accessSecret: MUST_SET_S3_ACCESSSECRET
    attachmentsBucket: MUST_SET_ATTACHMENTSBUCKET
 
server:
    minThreads: 4
    applicationConnectors:
        - type: http
          port: 8180
    adminConnectors:
        - type: http
          port: 8181
 
directory:
    url: "redis://localhost:6379/0"
 
cache:
    url: "redis://localhost:6379/1"
 
messageStore:
    driverClass: org.postgresql.Driver
    properties:
        charSet: UTF-8
 
database:
    driverClass: org.postgresql.Driver
    properties:
       charSet: UTF-8
    initialSize: 4
    minSize: 4
    maxSize: 8
 
limits:
    prekeys:
        bucketSize: 100
        leakRatePerMinute: 50
 
    messages:
        bucketSize: 1000
        leakRatePerMinute: 500
 
    attachments:
        bucketSize: 1000
        leakRatePerMinute: 100
 
    allocateDevice:
        bucketSize: 10
        leakRatePerMinute: 5
 
    verifyDevice:
        bucketSize: 10
        leakRatePerMinute: 5
